version: '3.8'

services:
  frontend:
    build:
      context: ./glasshub-frontend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    env_file:
      - ./glasshub-frontend/.env
    volumes:
      - ./glasshub-frontend:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./glasshub-backend
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    volumes:
      - ./glasshub-backend/uploads:/app/uploads
    env_file:
      - ./glasshub-backend/.env
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:13
    env_file:
      - ./glasshub-backend/.env
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres-data:

networks:
  app-network: